name: Run Frontend Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          cd codigo-fonte/front
          npm ci

      - name: Run tests with Jest GitHub Actions Reporter
        run: |
          cd codigo-fonte/front
          npm install --save-dev jest-github-actions-reporter
          npm test -- --reporters=default --reporters=jest-github-actions-reporter
